---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demo-site
  name: demo-site
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: demo-site
  template:
    metadata:
      labels:
        app: demo-site
    spec:
      containers:
      - image: nginx:latest
        imagePullPolicy: Always
        name: nginx-1006
        ports:
        - containerPort: 80
          protocol: TCP
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 3

---
apiVersion: v1
kind: Service
metadata:
  name: demo-site
  labels:
    app: demo-site
spec:
  ipFamily: IPv4
  externalTrafficPolicy: Local
  ports:
    - protocol: TCP
      nodePort: 30000
      port: 80
      targetPort: 80
  selector:
    app: demo-site
  type: LoadBalancer
